// src/assets/drivers.ts

export const persianDrivers = [
  {
    id: 1,
    name: "علی رضایی",
    pic: "images/m-1.jpg",
    license: "۱۲۳ن۹۵۷",
    model: "پژو ۲۰۶ آلبالویی",
  },
  {
    id: 2,
    name: "مهدی حسینی",
    pic: "images/m-2.jpg",
    license: "۴۵۶م۷۸۳",
    model: "پراید مشکی",
  },
  {
    id: 3,
    name: "سارا محمدی",
    pic: " images/f-13.jpg",
    license: "۷۸۹پ۲۴۱",
    model: "سمند سفید",
  },
  {
    id: 4,
    name: "محمد عباسی",
    pic: " images/m-3.jpg",
    license: "۳۴۵د۱۲۶",
    model: "دنا سفید",
  },
  {
    id: 5,
    name: "زهرا احمدی",
    pic: " images/f-14.jpg",
    license: "۲۱۳ر۴۷۸",
    model: "تیبا طوسی",
  },
  {
    id: 6,
    name: "فاطمه نوری",
    pic: " images/f-15.jpg",
    license: "۵۶۷ش۸۹۱",
    model: "پژو پارس سبز",
  },
  {
    id: 7,
    name: "رضا شریفی",
    pic: " images/m-4.jpg",
    license: "۶۷۸ص۳۲۴",
    model: "رانا نقره ای",
  },
  {
    id: 8,
    name: "حسین کریمی",
    pic: " images/m-5.jpg",
    license: "۹۱۲ل۶۵۷",
    model: "مزدا ۳ مشکی",
  },
  {
    id: 9,
    name: "نسیم قاسمی",
    pic: " images/f-17.jpg",
    license: "۴۵۶ک۷۸۹",
    model: "رنو استپ وی مشکی",
  },
  {
    id: 10,
    name: "امیر نیکزاد",
    pic: " images/m-6.jpg",
    license: "۳۴۸ه۱۲۴",
    model: "هیوندای امسنت مشکی",
  },
  {
    id: 11,
    name: "شهرزاد میری",
    pic: " images/f-17.jpg",
    license: "۵۷۶ط۹۰۳",
    model: "ساینا سفید",
  },
  {
    id: 12,
    name: "فرهاد مرادی",
    pic: " images/m-7.jpg",
    license: "۲۱۴گ۶۷۵",
    model: "پژو ۴۰۵ طوسی",
  },
  {
    id: 13,
    name: "شهاب داوودی",
    pic: " images/m-8.jpg",
    license: "۸۹۳ف۲۵۱",
    model: "کیا سراتو سفید",
  },
  {
    id: 14,
    name: "الناز شایان",
    pic: " images/f-18.jpg",
    license: "۱۲۷ب۹۸۲",
    model: "هیوندای توسان بنفش",
  },
  {
    id: 15,
    name: "نوید فراهانی",
    pic: " images/m-9.jpg",
    license: "۳۲۱خ۴۵۶",
    model: "چری تیگو مشکی",
  },
  {
    id: 16,
    name: "آرمان تقوی",
    pic: " images/m-10.jpg",
    license: "۴۵۸ش۶۷۸",
    model: "ام وی ام قرمز",
  },
  {
    id: 17,
    name: "پیمان یوسفی",
    pic: " images/m-11.jpg",
    license: "۹۸۷ن۲۳۵",
    model: "ساندرو مشکی",
  },
  {
    id: 18,
    name: "آرزو کاظمی",
    pic: " images/f-19.jpg",
    license: "۵۴۳ی۷۶۴",
    model: "ماکسیما نقره ای",
  },
  {
    id: 19,
    name: "نیما جمشیدی",
    pic: " images/m-12.jpg",
    license: "۷۳۶م۱۲۴",
    model: "پژو 2008 سفید",
  },
  {
    id: 20,
    name: "سپیده سلطانی",
    pic: " images/f-20.jpg",
    license: "۹۱۲ز۴۸۳",
    model: "سانگ یانگ بادمجونی",
  },
];
